version: '3'

services:
  app:
    build: .
    container_name: commerce-admin-app
    entrypoint: ./.docker/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    container_name: commerce-admin-db
    tty: true
    environment:
      - POSTGRES_DB=commerce_admin
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - commerce-admin-pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: commerce-admin-pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@fullcycle.com.br
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - "9000:80"

volumes:
  commerce-admin-pgdata:
     external: true