# Generated by Django 3.0.6 on 2020-06-01 18:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.TextField(max_length=255)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.Site')),
            ],
        ),
    ]
