# Generated by Django 3.0.6 on 2020-06-01 20:18

from django.db import migrations
import tenant.managers


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_auto_20200601_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTenant',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth_app.user',),
            managers=[
                ('objects', tenant.managers.UserTenantManager()),
            ],
        ),
    ]
